/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings src/worker/worker-configuration.d.ts` (hash: aa3612a64d6d29fde5341596347586f6)
interface __BaseEnv_CloudflareBindings {
  SESSIONS: KVNamespace;
  LOGIN_RATE_LIMITER: RateLimit;
  ASSETS: Fetcher;
  API_ORIGIN: string;
  API_TOKEN: string;
  WEB_ACCESS_PASSPHRASE: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
  }
  interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "API_ORIGIN" | "API_TOKEN" | "WEB_ACCESS_PASSPHRASE">
  > {}
}
