/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings src/worker-configuration.d.ts` (hash: f0570ddc3693b73c467610be2552615b)
interface __BaseEnv_CloudflareBindings {
	DB: D1Database;
	DEV_AUTH_USER_ID: "dev-user";
	DEV_AUTH_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEV_AUTH_USER_ID" | "DEV_AUTH_TOKEN">> {}
}
