/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings src/worker-configuration.d.ts` (hash: 13278dce5d562c433dd2615756b38f73)
interface __BaseEnv_CloudflareBindings {
	DB: D1Database;
	DEV_AUTH_USER_ID: string;
	CORS_ALLOWED_ORIGINS: string;
	DEV_AUTH_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEV_AUTH_USER_ID" | "CORS_ALLOWED_ORIGINS" | "DEV_AUTH_TOKEN">> {}
}
